version: '3.8'

services:
    express:
        container_name: express
        build: .
        restart: unless-stopped
        ports:
            - '3000:3000'
        env_file: .env
        depends_on:
            - mongo
            - redis
        networks:
            - app_net

    mongo:
        image: mongo:latest
        container_name: mongo
        restart: unless-stopped
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
        env_file: .env
        networks:
            - app_net

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        env_file: .env
        ports:
            - '6379:6379'
        command: redis-server --requirepass ${REDIS_PASSWORD} 
        volumes:
            - redis_data:/data
        networks:
            - app_net

volumes:
    mongodb_data:
    redis_data:

networks:
    app_net:
        driver: bridge
