import { randomBytes } from 'crypto';
import { nftList } from './creatorNftList';
import { Address, toNano } from '@ton/core';
import { IVoteItem } from './config/databaseTypes';

export const eventsList: IVoteItem[] = [
    {
        id: randomBytes(16).toString('hex'),
        title: `ФЛОР PEPE < 4К TON?`,
        shortDescription: `Будет ли флор коллекции гифтов PLUSH PEPE ниже, чем 4 000 TON до 18.06.25 по данным Portals Market`,
        description: '',
        tokenAddress: null,
        image: 'https://nft.fragment.com/collection/plushpepe.webp',
        creator: 'UQBNcONt7NKCn4YvcdeqU2HpiX94rL_a95kdR9L5pDkFhIzn',
        userId: 0,
        creatorNft: nftList[6],
        status: 'active',
        targetMcap: 0,
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('106').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('172').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-18T19:00:00Z').getTime(),
        collectedAmount: toNano(106 + 172).toString(),
        category: ['gift'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v1',
        contractAddress: '',
        startV1: toNano(106).toString(),
        startV2: toNano(172).toString(),
    },
    {
        id: '255d0d6eb67acbacb86c276d6be86a46',
        title: 'Запуск Бикбаева на 1M$+',
        shortDescription: 'Превысит ли MCap 1М$ в течение 24 часов после релиза 17 июня токена Бикбаева (дев $Alisher)',
        tokenAddress: null,
        description:
            'Исходом события является факт пробития ATH в 1М$ в течение 24 часов от листинга на токене запущенном Семёном Бикбаевым. Данные берутся с DEXSCREENER',
        image: 'https://static.daytona-project.com/images/Mcap.jpg',
        creator: 'UQAPLS1xQ7Gbo-L-3DfTS-Xcuj19mPJH6lFcKh4X-sO8jMkt',
        creatorNft: {
            address: '0:544BFE3213B36013E8741C43279CEDCC9158FFBFCBBB3904FE613CF0D5A248F3',
            symbol: '🍀',
            collection: 2,
            ownerFee: 0.075,
            serviceFee: 0.025,
            firstOwnerFee: 0,
            index: 116,
        },
        targetMcap: 1000000000,
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: '1135000000000',
                members: 2,
            },
            v2: {
                title: 'Нет',
                collected: '487000000000',
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: Date.now() + 60 * 1000 * 60,

        collectedAmount: '1205000000000',
        category: ['token'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v1',
        contractAddress: '',
        userId: 628122813,
    },

    {
        id: randomBytes(16).toString('hex'),
        title: `$RINS пробил 50K вверх?`,
        shortDescription: `RINS локально пробил 50К$ вверх до 16.06.25 в 17:00 по МСК`,
        description: '',
        tokenAddress: Address.parse('UQDHMh8yzqeb4YoH7-ZoyXw2vIRZ2xlO-v6pKjWX9CMhj1SX').toString(),
        image: 'https://static.opolyton.ru/rins.webp',
        creator: 'UQDHMh8yzqeb4YoH7-ZoyXw2vIRZ2xlO-v6pKjWX9CMhj1SX',
        userId: 0,
        creatorNft: nftList[110],
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('39').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('63').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-17T14:00:00Z').getTime(),
        collectedAmount: toNano(39 + 63).toString(),
        category: ['token'],
        targetMcap: 50000,
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v1',
        contractAddress: '',
        startV1: toNano(39).toString(),
        startV2: toNano(63).toString(),
    },
    {
        id: randomBytes(16).toString('hex'),
        title: `Сядет ли Смеркис?`,
        shortDescription: `Будет ли вынесен судом приговор с любым видом наказания ограничивающим свободу Владимиру Смеркису (CEO BLUM)`,
        description: '',
        tokenAddress: null,
        targetMcap: 0,
        image: 'https://static.opolyton.ru/smerk.jpg',
        creator: 'UQBNcONt7NKCn4YvcdeqU2HpiX94rL_a95kdR9L5pDkFhIzn',
        userId: 0,
        creatorNft: nftList[6],
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('202').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('381').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-16T14:00:00Z').getTime(),
        collectedAmount: toNano(202 + 381).toString(),
        category: ['activity'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v1',
        contractAddress: '',
        startV1: toNano(202).toString(),
        startV2: toNano(381).toString(),
    },

    {
        id: randomBytes(16).toString('hex'),
        title: `AKA пробил 400К$ вниз?`,
        shortDescription: `AKA локально пробил 400К$ вниз до 17.06.25 в 12:00 по МСК`,
        description: '',
        tokenAddress: 'EQBgCpDJVh1poEQS5ApQ0yg_K_J8SC9pdaMnlwPk7hjVClMQ',
        image: 'https://static.opolyton.ru/aka.jpg',
        targetMcap: 40000,
        creator: 'UQBNcONt7NKCn4YvcdeqU2HpiX94rL_a95kdR9L5pDkFhIzn',
        userId: 0,
        creatorNft: nftList[6],
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('132').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('83').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-18T09:00:00Z').getTime(),
        collectedAmount: toNano(132 + 83).toString(),
        category: ['token'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v2',
        contractAddress: '',
        startV1: toNano(132).toString(),
        startV2: toNano(83).toString(),
    },

    {
        id: randomBytes(16).toString('hex'),
        title: `TOSHKA пробил 800К$ вниз?`,
        shortDescription: `TOSHKA локально пробил 800К$ вниз до 17606.25 в 20:00 по МСК`,
        description: '',
        targetMcap: 800000,
        tokenAddress: 'EQBJBF7FKCRE6ClTG3NNUlWejM4Gaewa__vgFaBjJHoIDeuu',
        image: 'https://static.opolyton.ru/toshka.webp',
        creator: 'UQBNcONt7NKCn4YvcdeqU2HpiX94rL_a95kdR9L5pDkFhIzn',
        userId: 0,
        creatorNft: nftList[115],
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('42').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('67').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-18T17:00:00Z').getTime(),
        collectedAmount: toNano(42 + 67).toString(),
        category: ['token'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v2',
        contractAddress: '',
        startV1: toNano(42).toString(),
        startV2: toNano(67).toString(),
    },

    {
        id: randomBytes(16).toString('hex'),
        title: `FPI ПОСЛЕ РЕЛИЗА ПРОБИЛ 6М$?`,
        shortDescription: `FPI после релиза Апки 18 июня пробил 6М$ в течение 24 часов`,
        description: '',
        tokenAddress: 'EQD0KpcRMh-sKO2z5-vOjgvFjTT58tO-2Nmvxqg5ocFQFtWz',
        targetMcap: 6000000,
        image: 'https://static.opolyton.ru/fpi.png',
        creator: 'UQBNcONt7NKCn4YvcdeqU2HpiX94rL_a95kdR9L5pDkFhIzn',
        userId: 0,
        creatorNft: nftList[115],
        status: 'active',
        votes: {
            v1: {
                title: 'Да',
                collected: toNano('76').toString(),
                members: 0,
            },
            v2: {
                title: 'Нет',
                collected: toNano('91').toString(),
                members: 0,
            },
        },
        created_at: new Date(),
        expDateTimestamp: new Date('2025-06-19T09:00:00Z').getTime(),
        collectedAmount: toNano(76 + 91).toString(),
        category: ['token'],
        demoVotes: {
            v1: 0,
            v2: 0,
        },
        result: 'v1',
        contractAddress: '',
        startV1: toNano(76).toString(),
        startV2: toNano(91).toString(),
    },
];
